### ISSUE TITLE
NSS not switching services

### ISSUE THREAD

**Issue by alexeysilyuk** [foss-for-synopsys-dwc-arc-processors/glibc#2]
Hey!
I am trying to use my service for looking passwords, i wrote library libnss_myservice.so and inside i have function _nss_myservice_getpwnam_r , i put this library inside /lib/ directory. inside file /etc/nsswitch.conf i changed:
passwd:   files   myservice

but unfortunately on runtime, my service not invoked.
i have 2.26-73 version of glibc
please help me to solve this issue

**Comment by abrodkin** [comment]
@alexeysilyuk note this repo temporary contains Glibc sources with support of ARC CPU architecture.
That said if your problem has nothing to do with ARC port in particular I would advise you to post to upstream Glibc mailing list.

**Comment by alexeysilyuk** [comment]
my fault, i compiled my name service using g++ instead of gcc.
thanks
