### ISSUE TITLE
ARC support in glibc interferes with other architectures

### ISSUE THREAD

**Issue by cpackham** [foss-for-synopsys-dwc-arc-processors/glibc#7]
The code that determines what floating point support to enable [here](https://github.com/foss-for-synopsys-dwc-arc-processors/glibc/blob/abb73050766f12ec2fe2348fee39df658701c7c2/sysdeps/arc/preconfigure#L8) needs to be inside the `arc*)` case. Otherwise this overrides the with_fp_cond for other architectures when the glibc configure sources sysdeps/*/preconfigure

**Comment by vineetgarc** [comment]
Thx for the report. I've pushed ur fix to arc-glibc-master / arc-glibc-next branches !
